name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      steps:

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      
      - name: 'Build and push image'
        uses: docker/login-action@v1
        with:
          registry: registrymlopsloic.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . -t registrymlopsloic.azurecr.io/mlops:${{ github.sha }}
          docker push registrymlopsloic.azurecr.io/mlops:${{ github.sha }}

 