name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      steps:

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Docker Login'
        uses: azure/docker-login@v1
        with:
          login-server: registrymlopsloic.azurecr.io
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - run: |
          docker build . -t registrymlopsloic.azurecr.io/mlops:${{ github.sha }}
          docker push registrymlopsloic.azurecr.io/mlops:${{ github.sha }}
